version: "3.7"
services:
  saba:
    image: seungwook0417/saba:latest
    container_name: saba
#    build: .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - .:/app
    ports:
     - "8000:8000"
    env_file:
      - .env
