version: "3.7"
services:
  saba:
    image: test/saba:latest
    container_name: saba
    build: .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - .:/app
    ports:
     - "8002:8002"
    env_file:
      - .env

  clair:
    restart: always
    image: quay.io/projectquay/clair:nightly
    volumes:
      - ./clair/config.yaml:/config/config.yaml
    ports:
      - "6060:6060"
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    volumes:
      - ./clair/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: clair
      POSTGRES_USER: clair
      POSTGRES_PASSWORD: password
