version: "3.7"
services:
  saba:
    image: test/saba:latest
    container_name: saba
    build: .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - .:/app
    ports:
     - "8002:8002"
    env_file:
      - .env
