name: Hello

on: 
  # push:
  #   branches: [ "feat/action" ]
  workflow_dispatch:
    inputs:
      imageId:
        required: true
        type: string


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: install-dependencies 
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - id: running-code
        run: |
          python3 service/test.py     


