name: Hello

on: 
  push:
    branches: [ "feat/action" ]
  workflow_dispatch:
    inputs:
      imageId:
        required: true
        type: string


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: run-test
        run: |
          set -xe
          chmod +x .github/workflows/hello.sh
          .github/workflows/hello.sh ${{ github.event.inputs.imageId }}
          echo test ${{ steps.run-test.outputs }}
