name: Deploy to ECR

on:
 
  push:
    branches: [ KCH_ci_test ]

jobs:

  build:

    name: Build Image
    runs-on: ubuntu-latest

    steps:

    - name: Check out code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      
    - name: Build, tag, and push image to Amazon ECR
      run: |
        docker build -t saba_kch_ci_test .
        docker tag saba_kch_ci_test:latest 770939714089.dkr.ecr.ap-northeast-2.amazonaws.com/saba_kch_ci_test:latest
        docker push 770939714089.dkr.ecr.ap-northeast-2.amazonaws.com/saba_kch_ci_test:latest
