name: work CI test

on:
  push:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: start python
      run: 
        python service/test_service.py